name: Test

on:
  push:
    branches: [main]
  pull_request:

env:
  AWS_REGION: us-west-2
  PULUMI_CONFIG_PASSPHRASE: 123456

permissions:
  contents: read

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Pulumi
        uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2

      - name: Setup local Pulumi backend
        run: |
          pulumi login --local

      - name: Warmup pulumi new
        # TODO[pulumi/pulumi#21285]
        run: |
          mkdir /tmp/project
          pulumi new typescript --dir /tmp/project --yes

      - name: Run tests
        run: go test -v ./...
